import type { LegalDocumentContent } from "@/lib/legal/types";

export const cardsReminderPrivacyEn: LegalDocumentContent = {
  title: "Privacy Policy",
  lastUpdated: "Last updated: June 13, 2026",
  intro: [
    "This Privacy Policy describes how Lenara Labs (\"we\", \"our\", or \"the Company\") collects, uses, stores, and protects the personal information of users (\"you\" or \"the User\") of the CardsReminder mobile application (the \"App\"), available on iOS and developed by Lenara Labs.",
    "By downloading, registering, or using the App, you acknowledge that you have read and understood this Policy. If you do not agree with its terms, we recommend that you do not use the App.",
    "For privacy-related inquiries, you may contact us at hello@lenaralabs.com or visit lenaralabs.com.",
  ],
  sections: [
    {
      id: "controller",
      title: "1. Data controller",
      paragraphs: [
        "The data controller responsible for your personal data is Lenara Labs, with website at lenaralabs.com and contact email hello@lenaralabs.com.",
        "CardsReminder is a Lenara Labs product intended for users in Peru, Latin America, the United States, and other territories where the service may be useful.",
      ],
    },
    {
      id: "data-collected",
      title: "2. Data we collect",
      paragraphs: [
        "We collect only the information necessary to operate the App and provide its features. CardsReminder does not store full credit card numbers, banking credentials, financial institution passwords, or payment data processed by third parties.",
      ],
      subsections: [
        {
          id: "account-data",
          title: "2.1. Account and authentication data",
          list: [
            "Name and email address associated with your Google or Apple account when you use Google Sign-In or Apple Sign-In.",
            "Unique user identifier generated by Firebase Authentication.",
            "Authentication token required to maintain your session securely.",
          ],
        },
        {
          id: "card-data",
          title: "2.2. Card data entered by you",
          list: [
            "Custom alias or name for the card (for example, \"Gold Visa\").",
            "Visible last digits or partial reference you choose to record, never the full number.",
            "Billing, statement, due, and payment dates that you enter manually.",
            "Reminder preferences and notification settings associated with each card.",
          ],
        },
        {
          id: "usage-data",
          title: "2.3. Usage and device data",
          list: [
            "Device type, operating system version, and App version.",
            "Device identifier for push notification delivery (FCM token).",
            "Basic technical error and performance logs needed to maintain service stability.",
            "Language preferences and general App settings.",
          ],
        },
      ],
    },
    {
      id: "purpose",
      title: "3. How we use your data",
      list: [
        "Create, authenticate, and manage your user account.",
        "Display and organize your credit card information based on data you enter.",
        "Calculate and present payment date recommendations and usage suggestions based on registered information.",
        "Send push notifications about due dates, reminders, and alerts you configure.",
        "Maintain, protect, and improve the security, stability, and functionality of the App.",
        "Respond to support requests, inquiries, or privacy rights requests.",
        "Comply with applicable legal obligations when required.",
      ],
      paragraphs: [
        "We do not sell, rent, or trade your personal information to third parties for advertising purposes.",
      ],
    },
    {
      id: "legal-basis",
      title: "4. Legal basis for processing",
      paragraphs: [
        "We process your personal data on the following bases, as applicable in your jurisdiction:",
      ],
      list: [
        "Contract performance: to provide the CardsReminder service under the Terms and Conditions.",
        "Consent: when you enable push notifications or choose to link your account with Google or Apple.",
        "Legitimate interest: to ensure service security, prevent abuse, and improve the user experience.",
        "Legal obligation: when we must retain or disclose information under applicable law.",
      ],
    },
    {
      id: "third-parties",
      title: "5. Third-party services",
      paragraphs: [
        "We use trusted providers to operate the App. These third parties process data only according to our instructions and their own privacy policies:",
      ],
      subsections: [
        {
          id: "google",
          title: "5.1. Google Sign-In",
          paragraphs: [
            "If you choose to sign in with Google, Google will process certain authentication data under Google's Privacy Policy. We receive only the minimum information needed to identify your account within the App.",
          ],
        },
        {
          id: "apple",
          title: "5.2. Apple Sign-In",
          paragraphs: [
            "If you choose to sign in with Apple, Apple may provide us with your name and email address, or an Apple-generated relay email, depending on your privacy settings. Processing by Apple is governed by Apple's Privacy Policy.",
          ],
        },
        {
          id: "firebase",
          title: "5.3. Firebase (Google)",
          paragraphs: [
            "We use Firebase Authentication to manage sign-in and Firebase Cloud Messaging (FCM) to send push notifications. Firebase may process technical identifiers, device tokens, and metadata necessary to provide these services.",
          ],
        },
      ],
    },
    {
      id: "sharing",
      title: "6. Data sharing",
      paragraphs: [
        "We do not share your personal information with third parties except in the following cases:",
      ],
      list: [
        "With the technology providers described above, strictly to operate the App.",
        "When you expressly authorize us to do so.",
        "When necessary to comply with a legal obligation, competent authority request, or judicial proceeding.",
        "To protect the rights, safety, and integrity of Lenara Labs, users, or the public, when reasonably necessary.",
      ],
    },
    {
      id: "retention",
      title: "7. Data retention",
      paragraphs: [
        "We retain your personal information while you maintain an active CardsReminder account or as long as necessary to provide the service.",
        "If you request account deletion, we will delete or anonymize your personal data within a reasonable timeframe, unless we must retain it for legal obligations, dispute resolution, or fraud prevention.",
        "Technical and security logs may be retained for a limited additional period for audit and service protection purposes.",
      ],
    },
    {
      id: "security",
      title: "8. Information security",
      paragraphs: [
        "We implement reasonable technical and organizational measures to protect your information against unauthorized access, loss, alteration, or improper disclosure. These include encrypted communications, access controls, and secure development practices.",
        "No system is completely infallible. We therefore recommend protecting access to your device, using secure authentication methods enabled by your operating system, and not sharing your credentials with third parties.",
      ],
    },
    {
      id: "rights",
      title: "9. Your rights",
      paragraphs: [
        "Depending on applicable law in your country, you may have the right to:",
      ],
      list: [
        "Access the personal data we hold about you.",
        "Request correction of inaccurate or incomplete data.",
        "Request deletion of your personal data.",
        "Object to or restrict certain processing.",
        "Request data portability, where applicable.",
        "Withdraw your consent at any time, without affecting the lawfulness of prior processing.",
      ],
      subsections: [
        {
          id: "exercising-rights",
          title: "Exercising your rights",
          paragraphs: [
            "To exercise these rights, email us at hello@lenaralabs.com with your request and the information needed to verify your identity. We will respond within the timeframes required by applicable law.",
            "Users in Peru may exercise rights under Law No. 29733 (Personal Data Protection Law). Users in the European Union or United Kingdom, where applicable, may exercise rights under the GDPR. Users in California, where applicable, may have additional rights under the CCPA/CPRA.",
          ],
        },
      ],
    },
    {
      id: "minors",
      title: "10. Minors",
      paragraphs: [
        "CardsReminder is not directed at individuals under 18 years of age. We do not knowingly collect personal data from minors. If we discover that a minor has provided us with information, we will take reasonable steps to delete it.",
      ],
    },
    {
      id: "transfers",
      title: "11. International transfers",
      paragraphs: [
        "Your data may be processed on servers located outside your country of residence, including countries where Google, Apple, and Firebase operate. When this occurs, we will take reasonable measures to ensure an adequate level of protection under applicable law.",
      ],
    },
    {
      id: "changes",
      title: "12. Changes to this Policy",
      paragraphs: [
        "We may update this Privacy Policy from time to time. We will publish the current version at lenaralabs.com and, when changes are significant, notify you through the App or by email.",
        "We recommend reviewing this document periodically. Continued use of the App after changes are published will constitute acceptance of the updated Policy, unless the law requires additional consent.",
      ],
    },
    {
      id: "contact",
      title: "13. Contact",
      paragraphs: [
        "If you have questions, requests, or complaints related to this Privacy Policy, you may contact us at:",
        "Email: hello@lenaralabs.com",
        "Website: lenaralabs.com",
        "Controller: Lenara Labs",
      ],
    },
  ],
};
